#!/bin/bash  

if [ "$1" = "-c" ];then
    echo 'Changing Current Directory';
php /usr/bin/apachange.php -c
elif [ "$1" = "-r" ];then
    echo 'Restoring Default Directory';
    php /usr/bin/apachange.php -r
else
    php /usr/bin/apachange.php -a
fi
